version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "jdbc:postgresql://db:5432/postgres"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: postgres:latest
    volumes:
      - "./src/test/resources/database:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  e2e:
    build:
      context: .
      dockerfile: ./dockerfiles/e2e/Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      POSTGRES_URL: "jdbc:postgresql://db:5432/postgres"
    depends_on:
      - db
