name: ci on push
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run unittest
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yaml"
          test-container: "app"
          test-command: "gradle test"