name: ci on push
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run unittest
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
    # FIXME: if test failed, ci judges success